### ISSUE TITLE
[홈] 모임 검색 구현

### ISSUE THREAD

**Issue by ssumniee** [codestates/sweatmate#103]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 홈 화면의 모임 검색 구현

### TODO
1. [ ] 모임 검색 컴포넌트 뷰 구현
2. [ ] 검색 여부에 따른 리스트 뷰 조건부 렌더링 구현
3. [ ] 검색에 의한 서버와의 통신 구현
