### ISSUE TITLE
[재사용 컴포넌트] React Portals 활용해 컴포넌트 효율 높이기

### ISSUE THREAD

**Issue by ssumniee** [codestates/sweatmate#114]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: React Portals 활용해 컴포넌트 효율 높이기

### TODO
- [ ] React Portals 공부
- [ ] 모달 & 로딩 컴포넌트가 렌더링될 `modal-root` 태그 생성
- [ ] 모달 & 로딩 컴포넌트가 `modal-root` 태그 내부에 렌더링 되도록 코드 수정
