### ISSUE TITLE
[모임(채팅)] socket.IO 연결, 채팅 라우팅 구조 작성, mongoDB 스키마 작성

### ISSUE THREAD

**Issue by ghost** [codestates/sweatmate#127]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: socket.IO 연결, 채팅 Api 구현, mongoDB 스키마 작성
### TODO
1. [ ] socket.IO 연결
2. [ ] mongoDB 스키마 작성
3. [ ] 채팅 라우팅 구조 작성
