### ISSUE TITLE
[모임(채팅)] chat, gathering api 구현

### ISSUE THREAD

**Issue by ghost** [codestates/sweatmate#130]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: chat, gathering api, socketIO event 구현

### TODO
1. [ ] gathering에 mongodb 관련 코드 추가
2. [ ] chat api 구현
3. [ ] gathering, chat controller 에 socketIO 이벤트 구현
