### ISSUE TITLE
[재사용 컴포넌트] 재사용 컴포넌트 수정

### ISSUE THREAD

**Issue by ssumniee** [codestates/sweatmate#176]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Loading, GathCard, InputDatalist 컴포넌트 수정

### TODO
1. [ ] Loading 컴포넌트 수정  
  > isFullscreen에 따른 조건부 렌더링 CSS 코드 추가     
isFullscreen일 경우에만 동작하도록 배경 스크롤 제한 useEffect 함수 실행 조건 추가
2. [ ] GathCard 컴포넌트 수정
  > CSS 리팩토링
3. [ ] InputDatalist 컴포넌트 수정
  > (GlobalStyles에 추가한) 스크롤 바 표시 제한 CSS 코드 제거
