### ISSUE TITLE
[지도로 보기] 지도로 보기 로직 구현

### ISSUE THREAD

**Issue by heegu0311** [codestates/sweatmate#181]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 지도로보기 로직 구현

### TODO
1. [x] 좌표 변경시 새로운 데이터 받아오기
2. [x] 모임 마커 클릭시 오버레이 띄워주기
3. [x] 모임 마커 클릭시 해당 모임 카드에 하이라이트 및 스크롤 이동시켜주기

### Estimated time
> Pick one
### `3h`
