### ISSUE TITLE
[모임 상세] 모임 상세 모달 클릭 버튼 이벤트 로직 구현

### ISSUE THREAD

**Issue by ssumniee** [codestates/sweatmate#185]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 모임 상세 모달 클릭 버튼 이벤트 로직 구현

### TODO
1. [ ] 모임 참여하기 btn
2. [ ] 채팅방 바로가기 btn
3. [ ] 유저 썸네일 클릭 시 해당 유저 마이페이지로 리디렉션
