### ISSUE TITLE
[홈] 검색 영역 검색 관련 리덕스 state 업데이트 & 코드 리팩토링

### ISSUE THREAD

**Issue by ssumniee** [codestates/sweatmate#186]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 검색 영역 검색 관련 리덕스 상태 & CSS 코드 업데이트

### TODO
1. [ ] 검색 영역 검색 관련 리덕스 스토어의 state 수정
2. [ ] search bar 영역 코드 `Home.jsx`에서 분리 
3. [ ] (검색 인풋 컴포넌트들을 제외한) 반응형 CSS 전체적으로 업데이트
