### ISSUE TITLE
[재사용 컴포넌트] 모임 만들기 검색 인풋

### ISSUE THREAD

**Issue by heegu0311** [codestates/sweatmate#23]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 모임 만들기 검색 인풋 구현

### TODO
1. [ ] 모임 만들기 검색 인풋 구현
2. [ ] 스탭에 따른 검색 인풋 변화
3. [ ] 반응형 고려한 뷰 구현

### `2h`
