### ISSUE TITLE
[마이페이지] 마이페이지 로직 구현

### ISSUE THREAD

**Issue by heegu0311** [codestates/sweatmate#234]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: 마이페이지 로직 구현

### TODO
1. [x] 이미지 및 유저 정보 수정 기능 구현
2. [x] 유저 계정 삭제 기능 구현
3. [ ] 계정 삭제 확인 모달

### `3h`
