### ISSUE TITLE
[랜딩] (애니메이션을 제외한) 랜딩 페이지 구현 완료

### ISSUE THREAD

**Issue by ssumniee** [codestates/sweatmate#246]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: (애니메이션을 제외한) 랜딩 페이지 구현 완료

### TODO
1. [ ] 랜딩페이지 정적 뷰 구현 완료 (지도로 보기)
2. [ ] 모바일 대응을 위한 반응형 CSS 구현
3. [ ] 시작하기, 체험하기 버튼 로직 구현
