### ISSUE TITLE
[리팩토링] 클라이언트 뷰 개선 작업

### ISSUE THREAD

**Issue by ssumniee** [codestates/sweatmate#259]
### ISSUE
- Group:  `client`
- Type: `refactoring`
- Detail: 클라이언트 뷰 관련 코드 개선 및 수정 작업

### TODO
**컴포넌트 구조, CSS 관련 리팩토링 & 수정 작업**

* 마이페이지
1. [x] 모임 만들기 Step-by-step 검색창 디자인 홈과 매칭 작업

* 마이페이지
1. [x] 버튼 색상 바꾸기
2. [x] 큰 버튼은 width 조정으로 라인 맞추기
3. [x] 프로필 이미지 크기 사이즈

* 로그인 / 회원가입
1. [x] 로그인 인풋 닫힌 보더
2. [x] 로그인 / 회원가입 상단 여백 늘리기

* 헤더
1. [ ] 헤더게스트 로그인 / 로그인 버튼 디자인
2. [ ] 헤더 홈 채팅 일정 버튼 디자인

* 푸터
1. [ ] 푸터 Div 간격
2. [ ] 푸터 글자 색상

* 채팅방
1. [ ] 채팅방 리스트 뷰 글자 크기
2. [ ] 참여중인 메이트 부분 CSS

* 일정
1. [ ] 채팅방 리스트 뷰 글자 크기

* 모임 카드
1. [ ] 운동 이모지를 모두 이미지로 변경 (최 후순위 Linux OS 대응)
