### ISSUE TITLE
[재사용 컴포넌트] 유저 프로필 컴포넌트 재구현 & 모임 카드 컴포넌트 코드 수정

### ISSUE THREAD

**Issue by ssumniee** [codestates/sweatmate#34]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 

### TODO
1. [ ] 유저 프로필 컴포넌트 재구현 (닉네임까지 포함)
2. [ ] 유저 프로필 컴포넌트 조건부 로직 구현
3. [ ] 모임 카드 컴포넌트 코드 수정
