### ISSUE TITLE
[로그인 & 회원가입] 유저 정보 조회, 변경, 탈퇴 api 구현

### ISSUE THREAD

**Issue by ghost** [codestates/sweatmate#58]
### ISSUE
- Group:  `server`
- Type:`feature`
- Detail: 유저 정보 조회, 변경, 탈퇴 api 구현

### TODO
1. [ ] 유저 정보 조회
2. [ ] 유저 정보 변경
3. [ ] 회원 탈퇴 구현
