### ISSUE TITLE
[모임 상세] 모임 조기종료, 모임 참여/취소 api 구현

### ISSUE THREAD

**Issue by ghost** [codestates/sweatmate#99]
### ISSUE
- Group: `server`,
- Type: `feature`, 
- Detail: 모임 조기종료(모임 생성자는 모임을 조기 종료할 수 있습니다), (유저들의)모임 참여/취소 api 구현

### TODO
1. [ ] 모임 조기 종료 api 구현
2. [ ] 모임 참여 api 구현
3. [ ] 모임 참여취소 api구현
